INSERT INTO TIPOEQUIPO(ID,NOMBRE)
VALUES
(1,'cierra');

INSERT INTO TIPOEQUIPO(ID,NOMBRE)
VALUES
(2,'lijadora de banda');

INSERT INTO TIPOEQUIPO(ID,NOMBRE)
VALUES
(3,'mesa ensamblado');

INSERT INTO TIPOEQUIPO(ID,NOMBRE)
VALUES
(4,'fresadora');

INSERT INTO TIPOEQUIPO(ID,NOMBRE)
VALUES
(5,'Cepillo Garlopa');

INSERT INTO TIPOEQUIPO(ID,NOMBRE)
VALUES
(6,'dobladora');